project_name: EW
run_name: EW_2_3_e512_d512
model_name: enc_dec
root_dir: /pscratch/sd/p/pr4santh/results/symba
data_dir: /pscratch/sd/p/pr4santh/Data/permutation_free/EW-2-to-3/
device: cuda
epochs: 50
training_batch_size: 64
valid_batch_size: 64
num_workers: 128
embedding_size: 512
ff_dims: 4096
nhead: 8
num_encoder_layers: 3
num_decoder_layers: 4
warmup_ratio: 0.1
dropout: 0.2
weight_decay: 3e-4
optimizer_lr: 0.0005
src_max_len: 512
tgt_max_len: 512
curr_epoch: 0
save_last: true
filter_len: true
save_freq: 5
to_replace: true
index_pool_size: 1024
# truncate: true
# debug: true
